-- Table: profiles
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text default 'user', -- 'user' or 'admin'
  department text
);

-- Table: vehicles
create table vehicles (
  id bigint generated by default as identity primary key,
  name text not null, -- e.g., 'Toyota Camry'
  plate_number text not null,
  capacity int,
  image_url text,
  status text default 'active' -- 'active', 'maintenance'
);

-- Table: bookings
create table bookings (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  user_id uuid references profiles(id),
  vehicle_id bigint references vehicles(id),
  start_time timestamptz not null,
  end_time timestamptz not null,
  purpose text,
  status text default 'pending' -- 'pending', 'approved', 'rejected'
);

-- Seed some initial data
INSERT INTO vehicles (name, plate_number, capacity, status) VALUES
('Toyota Camry', 'กข-1234', 4, 'active'),
('Honda CRV', 'ขอ-5678', 5, 'active'),
('Toyota Commuter', 'ฮฮ-9999', 11, 'active');
